[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

monitor_filters = 
  colorize
  time

lib_deps = 
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit INA219 @ ^1.2.3
  miguelbalboa/MFRC522 @ ^1.4.12
  mikalhart/TinyGPSPlus @ ^1.1.0
  bblanchon/ArduinoJson @ ^6.21.5
